stages:
  - build
  - test
  - deploy

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml"
  TRUSTSTORE_PASSWORD: $TRUSTSTORE_PASSWORD
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Xmx512m -Djavax.net.ssl.trustStore=.m2/maven.truststore -Djavax.net.ssl.trustStorePassword=$TRUSTSTORE_PASSWORD"

include:
  - template: Security/Secret-Detection.gitlab-ci.yml

secret_detection:
  variables:
    SECRET_DETECTION_HISTORIC_SCAN: "true"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/maven:3-openjdk-8-slim
  stage: build
  script:
    - echo "---- GITLAB CI/CD KLEMEN SCRIPT ------ stage build"
    - echo "MAVEN_OPTS:" $MAVEN_OPTS
    - ls -all ./src/main/filters
    - mkdir -p /builds/erenderwebui/dis/Dis-shared/src/main
    - mkdir -p /builds/erenderwebui/dis/Dis-server/src/main
    - mkdir -p /builds/erenderwebui/dis/Dis-client/src/main
    - ln -s ./src/main/filters /builds/erenderwebui/dis/Dis-shared/src/main/filters
    - ls -li ./Dis-shared/src/main/filters
    - ln -s ./src/main/filters /builds/erenderwebui/dis/Dis-client/src/main/filters
    - ln -s ./src/main/filters /builds/erenderwebui/dis/Dis-server/src/main/filters
    - echo "---SHOW FILES ----"
    - ls -all /builds/erenderwebui/dis/Dis-shared/src/main/filters/*.*
    - mvn $MAVEN_CLI_OPTS clean compile -P test -Dgwt.skipCompilation=true -e -X
  artifacts:
    paths:
      - ./target



test:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/maven:3-openjdk-8-slim
  stage: test
  script:
    - echo "---- GITLAB CI/CD KLEMEN SCRIPT ------ stage test"
    - echo "MAVEN_OPTS:" $MAVEN_OPTS
    - ln -s ./src/main/filters ./Dis-shared/src/main/filters
    - ln -s ./src/main/filters ./Dis-client/src/main/filters
    - ln -s ./src/main/filters ./Dis-server/src/main/filters
    - mvn $MAVEN_CLI_OPTS test -P test -Dgwt.skipCompilation=true
  artifacts:
    paths:
      - ./target

deploy:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/maven:3-openjdk-8-slim
  stage: deploy
  script:
    - echo "---- GITLAB CI/CD KLEMEN SCRIPT ------ stage deploy"
    - echo "MAVEN_OPTS:" $MAVEN_OPTS
    - ln -s ./src/main/filters ./Dis-shared/src/main/filters
    - ln -s ./src/main/filters ./Dis-client/src/main/filters
    - ln -s ./src/main/filters ./Dis-server/src/main/filters
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - master
  artifacts:
    paths:
      - ./target
