stages:
  - build
  - test
  - deploy

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml"
  TRUSTSTORE_PASSWORD: $TRUSTSTORE_PASSWORD
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Xmx512m -Djavax.net.ssl.trustStore=.m2/maven.truststore -Djavax.net.ssl.trustStorePassword=$TRUSTSTORE_PASSWORD -Dsettings.security=.m2/security-settings.xml"
  OC_NAMESPACESLUG: dis-dev
  OC_URL_DEV: https://api.okd-test.ts.telekom.si:6443
  OC_URL_TEST: https://api.ocp-test.ts.telekom.si:6443
  OC_URL_PROD: https://api.ocp-prod.ts.telekom.si:6443

include:
  - template: Security/Secret-Detection.gitlab-ci.yml

secret_detection:
  variables:
    SECRET_DETECTION_HISTORIC_SCAN: "true"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/maven:3-openjdk-8-slim
  stage: build
  script:
    - echo "---- GITLAB CI/CD KLEMEN SCRIPT ------ stage build"
    - echo "MAVEN_OPTS:" $MAVEN_OPTS
    - pwd
    - ls -all ./src/main/filters
    - mkdir -p /builds/erenderwebui/dis/Dis-shared/src/main
    - mkdir -p /builds/erenderwebui/dis/Dis-server/src/main
    - mkdir -p /builds/erenderwebui/dis/Dis-client/src/main
    - ln -s /builds/erenderwebui/dis/src/main/filters ./Dis-shared/src/main/filters
    - ln -s /builds/erenderwebui/dis/src/main/filters ./Dis-client/src/main/filters
    - ln -s /builds/erenderwebui/dis/src/main/filters ./Dis-server/src/main/filters
    - echo "---SHOW FILES ----"
    - ls -all /builds/erenderwebui/dis/Dis-shared/src/main/filters/*.*
    - mvn $MAVEN_CLI_OPTS clean compile -P test -Dgwt.skipCompilation=true
  artifacts:
    paths:
      - ./target


test:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/maven:3-openjdk-8-slim
  stage: test
  script:
    - echo "---- GITLAB CI/CD KLEMEN SCRIPT ------ stage test"
    - echo "MAVEN_OPTS:" $MAVEN_OPTS
    - ln -s /builds/erenderwebui/dis/src/main/filters ./Dis-shared/src/main/filters
    - ln -s /builds/erenderwebui/dis/src/main/filters ./Dis-client/src/main/filters
    - ln -s /builds/erenderwebui/dis/src/main/filters ./Dis-server/src/main/filters
    - sudo apt-get install net-tools
		- sudo netstat –tulnp
    - mvn $MAVEN_CLI_OPTS test -P test -Dgwt.skipCompilation=true
  artifacts:
    paths:
      - ./target

deploy:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/maven:3-openjdk-8-slim
  stage: deploy
  script:
    - echo "---- GITLAB CI/CD KLEMEN SCRIPT ------ stage deploy"
# https://console-openshift-console.apps.okd-test.ts.telekom.si/k8s/ns/dis-dev/pods/dis-5454fc4484-9jjjm/terminal
    - oc login $OC_URL_TEST --token=$OC_TOKEN_TEST
    - oc status
  only:
    - master
  artifacts:
    paths:
      - ./target


