version: "3.5"

services:
  collabora:
    image: collabora/code
    restart: unless-stopped
    environment:
#      - DONT_GEN_SSL_CERT="false"
#      - extra_params=--o:ssl.enable=false --o:ssl.termination=false --o:net.proto=IPv4
      - extra_params=--o:net.proto=IPv4
      - username=admin
      - password=admin
      - dictionaries=en_US
      - domain=erender-test.ts.telekom.si
      - server_name=klemen-HP-EliteBook-850-G7-Notebook-PC.ts.telekom.si
      - domain=ts.telekom.si
    cap_add:
      - MKNOD
    ports:
      - "9980:9980"
    container_name: collabora
    volumes:
      - ${PWD}/src/main/resources/docker:/etc/loolwsd/certs
      - ${PWD}/src/main/resources/docker/loolwsd.xml:/etc/loolwsd/loolwsd.xml
    privileged: true

#  wopivalidator:
#    image: tylerbutler/wopi-validator
#    restart: unless-stopped

