apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: wopivalidator
  name: wopivalidator
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: wopivalidator
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: wopivalidator
    spec:
      containers:
      - image: tylerbutler/wopi-validator
        imagePullPolicy: ""
        name: wopivalidator
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
