openapi: 3.0.3
servers:
  - url: https://erender-test.ts.telekom.si:8445/api/v1/dis-dev
    description: Test server
  - url: https://erender-test.ts.telekom.si:8445/api/v1/dis-test
    description: Test server
  - url: https://erender-test.ts.telekom.si:8445/api/v1/dis
    description: Prod server
info:
  version: "1.0.1"
  title: Dis API
paths:
  /documents:
    post:
      tags:
       - provisioning
      summary: gets documents
      operationId: getDocuments
      description: gets documents in Dis
      security:
        - BasicAuth: []
      parameters:
        - in: header
          name: 'X-Transaction-Id'
          schema:
            type: string
          example: '123e4567-e89b-12d3-a456-426614174000'
        - in: query
          name: r_object_id
          description: unique document identifier
          required: false
          schema:
            type: string          
        - in: query
          name: dql
          description: dql to retrieve document
          required: false
          schema:
            type: string     
      responses:
        '200':
          description: 'success'    
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentsResponse'
        '500':
          description: 'internal server error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /documents/{r_object_id}/getContent/{format}:
    get:
      tags:
       - provisioning
      summary: get content url of document
      operationId: getContent
      description: retrieve content of document in Dis platform
      security:
        - BasicAuth: []
      parameters:
        - in: header
          name: 'X-Transaction-Id'
          schema:
            type: string
          example: '123e4567-e89b-12d3-a456-426614174000'
        - in: path
          name: r_object_id
          description: unique document identifier
          required: true
          schema:
            type: string
        - in: path
          name: format
          description: format of document or null for primary content
          required: true
          schema:
            type: string            
      responses:
        '200':
          description: 'success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentsResponse'
          
        '500':
          description: 'internal server error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /documents/newDocument:
    post:
      tags:
       - provisioning
      summary: creates a new document
      operationId: createDocument
      description: creates a new document in Dis
      security:
        - BasicAuth: []
      parameters:
        - in: header
          name: 'X-Transaction-Id'
          schema:
            type: string
          example: '123e4567-e89b-12d3-a456-426614174000'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewDocumentRequest'
      responses:
        '200':
          description: 'success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
        '500':
          description: 'internal server error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /documents/importDocument:
    post:
      tags:
       - provisioning
      summary: import a new document
      operationId: importDocument
      description: imports a new document in Dis
      security:
        - BasicAuth: []
      parameters:
        - in: header
          name: 'X-Transaction-Id'
          schema:
            type: string
          example: '123e4567-e89b-12d3-a456-426614174000'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ImportDocumentRequest'
      responses:
        '200':
          description: 'success'    
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
        '500':
          description: 'internal server error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              
  /documents/{r_object_id}/promote:
    post:
      tags:
       - provisioning
      summary: promote document
      operationId: promoteDocument
      description: promote the document in Dis platform
      security:
        - BasicAuth: []
      parameters:
        - in: header
          name: 'X-Transaction-Id'
          schema:
            type: string
          example: '123e4567-e89b-12d3-a456-426614174000'
        - in: path
          name: r_object_id
          description: unique document identifier
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'          
        '500':
          description: 'internal server error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                
  /documents/{r_object_id}/demote:
    post:
      tags:
       - provisioning
      summary: demote document
      operationId: demoteDocument
      description: demote the document in Dis platform
      security:
        - BasicAuth: []
      parameters:
        - in: header
          name: 'X-Transaction-Id'
          schema:
            type: string
          example: '123e4567-e89b-12d3-a456-426614174000'
        - in: path
          name: r_object_id
          description: unique document identifier
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'success'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
        '500':
          description: 'internal server error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  headers:
    XTransactionId:
      description: Global transaction identifier
      schema:
        type: string
      example: '123e4567-e89b-12d3-a456-426614174000'
  schemas:
    NewDocumentRequest:
      type: object
      required:
        - profileId
        - attributes
        - rolesUsers
        - templateObjectRObjectId
        - stateId        
      properties:
        profileId:
          type: string
          description: id of profile in DIS sistem
          example: "mob_subscriber_document"      
        attributes:
          type: array
          description: A list of attributes to be set on document
          items:
            $ref: "#/components/schemas/Attribute"
        rolesUsers:
          type: array
          description: A list of attributes to be set on document
          items:
            $ref: "#/components/schemas/RoleUsers"
        templateObjectRObjectId:
          type: string
          description: r_object_id of object
          example: 0900000191cfbdf8
        stateId:
          type: string
          description: target state of document to which neewdocument would be set to
          example: any of "draft" "effective" "archive" or other state that is specied in profile for profile               
    ImportDocumentRequest:
      type: object
      required:
        - profileId
        - attributes
        - rolesUsers
        - contentBase64
        - format
        - stateId
      properties:
        profileId:
          type: string
          description: id of profile in DIS sistem
          example: "mob_subscriber_document"        
        attributes:
          type: array
          description: A list of attributes to be set on document
          items:
            $ref: "#/components/schemas/Attribute"
        rolesUsers:
          type: array
          description: A list of attributes to be set on document
          items:
            $ref: "#/components/schemas/RoleUsers"
        contentBase64:
          type: string
          description: content of document
          example: 
        format:
          type: string
          description: documentum format of document
          example: any of "odt" "msw12" "excelbook"
        stateId:
          type: string
          description: target state of document to import to
          example: any of "draft" "effective" "archive" or other state that is specied in profile for profile     
    Attribute:
      type: object
      properties:
        name:
          type: string
          description: attribute name 
          example: "title"
        values:
          type: array
          description: values of atribute
          example: { "value1", "value2" } 
          items:
            type: string

    RoleUsers:
      type: object
      properties:
        roleName:
          type: string
          description: role name
          example: example roles are one of "coordinator", "user", "administrator", "erender"
        values:
          type: array
          description: name of users or groups from AD that are synced in content management system
          example: { "raifk", "lokart", "dm_world", "" } 
          items:
            type: string


            
    DocumentsResponse:
      type: object
      properties:
        documents:
          type: array
          description: array od documents
          items:
            $ref: "#/components/schemas/Document"
      required:
        - documents     
             

    Document:
      type: object
      description: Document from content management system
      properties:
        rObjectId:
          type: string
          description: rObjectId unique identifier from content management system
          example: 0900000191cdbe4c
        objectName:
          type: string
          description: rObjectId unique identifier from content management system
          example: 0900000191cdbe4c
        releaseNumber:
          type: integer
          description: release nuber of docuent
          example: 0
        
    PromoteDemoteDocumentRequest:
      type: object
      description: reponse of promote and demote operation
      properties:
        rObjectId:
          type: string
          description: rObjectId unique identifier from content management system could be change during operation
          example: 0900000191cdbe4c

    Error:
      type: object
      required:
        - code
        - reason
      properties:
        code:
          type: string
          description: Application related code.
        reason:
          type: string
          description: Text that explains the reason for error.
        message:
          type: string
          description: (optional) Text that provides more details and corrective actions related to the error.
        referenceError:
          $ref: '#/components/schemas/Error'