openapi: 3.0.3
servers:
- url: https://erender-test.ts.telekom.si:8445/api
  description: wopi interface to support collabora edit of documents
info:
  version: 1.0.1
  title: Dis API
security: 
  - ApiKeyAuth: []
paths:
  /wopi/files/{document}:
    get:
      tags:
        - wopi.v2
      summary: CheckFileInfo
      operationId: getCheckFileInfo
      parameters:
        - name: document
          in: path
          required: true
          description: "The document id"
          schema:
            type: string
        - name: access_token
          in: query
          required: true
          description: An access token to access the document
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileInfo'
        "401":
          description: Unauthorized
        "404":
          description: Not found
        "500":
          description: Server error
  /wopi/files/{document}/contents:
    get:
      tags:
        - wopi.v2
      summary: Get document contents
      operationId: getWopiDocumentContent
      parameters:
        - name: document
          in: path
          required: true
          description: "The document id"
          schema:
            type: string
        - name: access_token
          in: query
          required: true
          description: An access token to access the document
          schema:
            type: string
      responses:
        "200":
          description: Contents
        "403":
          description: Access denied
        "404":
          description: Resource does not exists
    post:
      tags:
        - wopi.v2
      summary: Save document contents
      operationId: updateWopiDocumentContent
      parameters:
        - name: document
          in: path
          required: true
          description: "The document id"
          schema:
            type: string
        - name: access_token
          in: query
          required: true
          description: An access token to access the document
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: string
        description: Document content
      responses:
        "200":
          description: Operation was successful
        "403":
          description: Access denied
        "404":
          description: Resource does not exists
          
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
  schemas:
    FileInfo:
      type: object
      required:
      - baseFileName
      - size
      - ownerId
      - version
      - sha256
      - allowExternalMarketplace
      - userCanWrite
      - supportsUpdate
      - supportsLock
      properties:
        BaseFileName:
          type: string
          description: basefilename
          example: wwerwre
        Size:
          type: long
          description: velikost
          example: 200
        OwnerId:
          type: string
          description: owner
          example: me
        UserId:
          type: string
          description: owner
          example: me
        Version:
          type: long
          description: owner
          example: me
        Sha256:
          type: string
          description: sha256
          example: 2342423424
        AllowExternalMarketplace:
          type: boolean
          description: externalmarketplace
          example: true
        UserCanWrite:
          type: boolean
          description: can user write
          example: true
        SupportsUpdate:
          type: boolean
          description: supportsupdate?
          example: true
        SupportsLocks:
          type: boolean
          description: supportsLock?
          example: true
        LastModifiedTime:
          type: string
          description: last modified time in ISO 8601 formated string
        UserFriendlyName:
          type: string
          description: user friendly name
