openapi: 3.0.3
servers:
- url: https://erender-test.ts.telekom.si:8445/api
  description: wopi interface to support collabora edit of documents
info:
  version: 1.0.1
  title: Dis API
security: 
  - ApiKeyAuth: []
paths:
  /wopi/files/{document}:
    get:
      tags:
        - wopi.v2
      summary: CheckFileInfo
      operationId: getCheckFileInfo
      parameters:
        - name: document
          in: path
          required: true
          description: "The document id"
          schema:
            type: string
        - name: access_token
          in: query
          required: true
          description: An access token to access the document
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileInfo'
        "401":
          description: Unauthorized
        "404":
          description: Not found
        "500":
          description: Server error
# https://docs.microsoft.com/en-us/microsoft-365/cloud-storage-partner-program/rest/files/lock
    post:
      tags:
        - wopi.v2
      summary: Lock document
      operationId: lockDocument
      parameters:
        - name: document
          in: path
          required: true
          description: "The document id"
          schema:
            type: string
        - name: access_token
          in: query
          required: true
          description: An access token to access the document
          schema:
            type: string
        - in: header
          name: X-WOPI-Lock
          required: true
          description: A string provided by the WOPI client that the host must use to identify the lock on the file. Required.
          schema:
            type: string
        - in: header
          name: X-WOPI-Override
          required: false
          description: The string UNLOCK. Required.
          schema:
            type: string                 
      requestBody:
        content:
          application/json:
            schema:
              type: string
        description: Document content
      responses:
        "200":
          description: Lock was successful
        "400":
          description: X-WOPI-Lock was not provided or was empty
        "401":
          description: unauthorized - Invalid access token
        "404":
          description: Resource not found/user unauthorized      
        "409":
          description: Conflict - Lock mismatch/locked by another interface; an X-WOPI-Lock response header containing the value of the current lock on the file must always be included when using this response code          
        "500":
          description: Internal server error        
  /wopi/files/{document}/contents:
    get:
      tags:
        - wopi.v2
      summary: Get document contents
      operationId: getWopiDocumentContent
      parameters:
        - name: document
          in: path
          required: true
          description: "The document id"
          schema:
            type: string
        - name: access_token
          in: query
          required: true
          description: An access token to access the document
          schema:
            type: string
      responses:
        "200":
          description: Contents
        "403":
          description: Access denied
        "404":
          description: Resource does not exists
    post:
      tags:
        - wopi.v2
      summary: Save document contents
      operationId: updateWopiDocumentContent
      parameters:
        - name: document
          in: path
          required: true
          description: "The document id"
          schema:
            type: string
        - name: X-LOOL-WOPI-IsModifiedByUser
          in: header
          required: false
          description: if document modified by user will have the value true or false accordingly.
          schema:
            type: boolean    
        - name: X-LOOL-WOPI-IsAutosave
          in: header
          required: false
          description: will have the value true when the PutFile is triggered by auto-save, and false when triggered by explicit user operation (Save button or menu entry)
          schema:
            type: boolean    
        - name: X-LOOL-WOPI-IsExitSave
          in: header
          required: false
          description: When the document gets cleaned up from memory (e.g. when all users disconnect), an automatic save will be triggered. In this case the following header will be set to true
          schema:
            type: boolean
        - name: X-LOOL-WOPI-Timestamp
          in: header
          required: false
          description: ISO8601 round-trip formatted time of file’s last modified time in storage, as known by Collabora Online. In case this header is present and its value does not match the file’s modified time in storage, it indicates that document being edited is not the one that is present in the storage. Hosts should not save the file to storage in such cases and respond with HTTP 409 along with Collabora Online specific status code 409 in json
          schema:
            type: string   
        - name: access_token
          in: query
          required: true
          description: An access token to access the document
          schema:
            type: string
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
        description: Document content
      responses:
        "200":
          description: Operation was successful
        "401":
          description: Unautorized
        "403":
          description: Access denied
        "404":
          description: Not found        
        "409":
          description: Conflict - Lock mismatch/locked by another interface; an X-WOPI-Lock response header containing the value of the current lock on the file must always be included when using this response code
        "413":
          description: Request entity too large - File is too large; the maximum file size is host-specific        
        "500":
          description: Server error        
        "501":
          description: Not implemented        
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
  schemas:
    FileInfo:
      type: object
      required:
      - BaseFileName
      - DisablePrint
      - OwnerId
      - PostMessageOrigin
      - Size
      - TemplateSource
      - UserCanWrite
      - UserCanNotWriteRelative
      - UserId
      - UserFriendlyName
      - LastModifiedTime
      - Version
      - Sha256
      - SupportsUpdate
      - SupportsLock
      - HidePrintOption
      - HideSaveOption
      - HideExportOption
      - DisableExport
      - DisableCopy
      - DisableInactiveMessages
      - DownloadAsPostMessage
      - EnableOwnerTermination
      - UserExtraInfo
      - WatermarkText
      properties:
        BaseFileName:
          type: string
          description: The string name of the file, including extension, without a path. Used for display in user interface (UI), and determining the extension of the file.
          example: wwerwre
        DisablePrint:
          type: boolean
          description: A Boolean value that indicates the WOPI client should disable all print functionality.
          example: true          
        OwnerId:
          type: string
          description: A string that uniquely identifies the owner of the file. In most cases, the user who uploaded or created the file should be considered the owner.
          example: me
        PostMessageOrigin:
          type: string
          description: A string value indicating the domain the host page will be sending/receiving PostMessages to/from. Office Online will only send outgoing PostMessages to this domain, and will only listen to PostMessages from this domain.
          example: me
        Size:
          type: long
          description: Size of the file in bytes (64bit)
          example: 200
        TemplateSource:
          type: string
          description: The ID of file (like the wopi/files/ID) can be a non-existing file. In that case, the file will be created from a template when the template (eg. an OTT file) is specified as TemplateSource in the CheckFileInfo response. For the actual saving of the content, normal PutFile mechanism will be used.
          example: https://somewhere/accessible/file.ott
        UserCanWrite:
          type: boolean
          description: A boolean flag, indicating whether the user has permission to edit and/or over-write the file. If not set PutFile will fail.
          example: true
        UserCanNotWriteRelative:
          type: boolean
          description: A boolean flag indicating that the user cannot Save-As on this server, so PutFileRelative will fail.
          example: true                    
        UserId:
          type: string
          description: A programmatic string identifier of the user.
          example: me
        UserFriendlyName:
          type: String
          description: A string that is the name of the user, suitable for displaying in UI.
          example: me
        LastModifiedTime:
          type: string
          description: last modified time in ISO 8601 formated string
        Version:
          type: string
          description: The current version of the file based on the server’s file version schema, as a string. This value must change when the file changes, and version values must never repeat for a given file.
        Sha256:
          type: string
          description: sha256
          example: 2342423424          
        SupportsUpdate:
          type: boolean
          description: supportsupdate?
          example: true
        SupportsLocks:
          type: boolean
          description: supportsLock?
          example: true          
        HidePrintOption:
          type: boolean
          description: externalmarketplace
          example: true            
        HideSaveOption:
          type: boolean
          description: externalmarketplace
          example: true 
        HideExportOption:
          type: boolean
          description: externalmarketplace
          example: true
        DisableExport:
          type: boolean
          description: externalmarketplace
          example: true 
        DisableCopy:
          type: boolean
          description: externalmarketplace
          example: true 
        DisableInactiveMessages:
          type: boolean
          description: externalmarketplace
          example: true
        DownloadAsPostMessage:
          type: boolean
          description: externalmarketplace
          example: true
        EnableOwnerTermination:
          type: boolean
          description: externalmarketplace
          example: true            
        UserExtraInfo:
          type: string
          description: owner
          example: me
        WatermarkText:
          type: string
          description: owner
          example: me                    
        AllowExternalMarketplace:
          type: boolean
          description: externalmarketplace
          example: true
