
package si.telekom.services.common.customer.v1;

import javax.xml.ws.WebFault;
import si.telekom.services.common.base.v1.ServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "customerServiceException", targetNamespace = "http://telekom.si/services/common/customer/v1")
public class CustomerServiceException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ServiceException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CustomerServiceException(String message, ServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public CustomerServiceException(String message, ServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: si.telekom.services.common.base.v1.ServiceException
     */
    public ServiceException getFaultInfo() {
        return faultInfo;
    }

}
