
package si.telekom.services.common.customer.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import si.telekom.services.common.base.v1.GetSystemInfoRequestMsg;
import si.telekom.services.common.base.v1.GetSystemInfoResponseMsg;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ICustomerService", targetNamespace = "http://telekom.si/services/common/customer/v1")
@XmlSeeAlso({
    si.telekom.schemas.product.usage.v1.ObjectFactory.class,
    si.telekom.schemas.resource.management.v1.ObjectFactory.class,
    si.telekom.schemas.product.fulfillment.v1.ObjectFactory.class,
    si.telekom.schemas.common.base.v1.ObjectFactory.class,
    si.telekom.schemas.common.businessinteraction.v1.ObjectFactory.class,
    si.telekom.schemas.common.customer.v1.ObjectFactory.class,
    si.telekom.schemas.common.dealer.v1.ObjectFactory.class,
    si.telekom.schemas.common.location.v1.ObjectFactory.class,
    si.telekom.schemas.common.party.v1.ObjectFactory.class,
    si.telekom.schemas.product.lifecycle.v1.ObjectFactory.class,
    si.telekom.services.common.base.v1.ObjectFactory.class,
    si.telekom.services.common.customer.v1.ObjectFactory.class
})
public interface ICustomerService {


    /**
     * 
     * @param createCustomerRequestMsg
     * @return
     *     returns si.telekom.services.common.customer.v1.CreateCustomerResponseMsg
     * @throws CustomerServiceException
     */
    @WebMethod(action = "http://telekom.si/services/common/customer/v1/createCustomer")
    @WebResult(name = "createCustomerResponseMsg", targetNamespace = "http://telekom.si/services/common/customer/v1")
    @RequestWrapper(localName = "createCustomer", targetNamespace = "http://telekom.si/services/common/customer/v1", className = "si.telekom.services.common.customer.v1.CreateCustomer")
    @ResponseWrapper(localName = "createCustomerResponse", targetNamespace = "http://telekom.si/services/common/customer/v1", className = "si.telekom.services.common.customer.v1.CreateCustomerResponse")
    public CreateCustomerResponseMsg createCustomer(
        @WebParam(name = "createCustomerRequestMsg", targetNamespace = "http://telekom.si/services/common/customer/v1")
        CreateCustomerRequestMsg createCustomerRequestMsg)
        throws CustomerServiceException
    ;

    /**
     * 
     * @param findCustomerRequestMsg
     * @return
     *     returns si.telekom.services.common.customer.v1.FindCustomerResponseMsg
     * @throws CustomerServiceException
     */
    @WebMethod(action = "http://telekom.si/services/common/customer/v1/findCustomer")
    @WebResult(name = "findCustomerResponseMsg", targetNamespace = "http://telekom.si/services/common/customer/v1")
    @RequestWrapper(localName = "findCustomer", targetNamespace = "http://telekom.si/services/common/customer/v1", className = "si.telekom.services.common.customer.v1.FindCustomer")
    @ResponseWrapper(localName = "findCustomerResponse", targetNamespace = "http://telekom.si/services/common/customer/v1", className = "si.telekom.services.common.customer.v1.FindCustomerResponse")
    public FindCustomerResponseMsg findCustomer(
        @WebParam(name = "findCustomerRequestMsg", targetNamespace = "http://telekom.si/services/common/customer/v1")
        FindCustomerRequestMsg findCustomerRequestMsg)
        throws CustomerServiceException
    ;

    /**
     * 
     * @param getCustomerRequestMsg
     * @return
     *     returns si.telekom.services.common.customer.v1.GetCustomerResponseMsg
     * @throws CustomerServiceException
     */
    @WebMethod(action = "http://telekom.si/services/common/customer/v1/getCustomer")
    @WebResult(name = "getCustomerResponseMsg", targetNamespace = "http://telekom.si/services/common/customer/v1")
    @RequestWrapper(localName = "getCustomer", targetNamespace = "http://telekom.si/services/common/customer/v1", className = "si.telekom.services.common.customer.v1.GetCustomer")
    @ResponseWrapper(localName = "getCustomerResponse", targetNamespace = "http://telekom.si/services/common/customer/v1", className = "si.telekom.services.common.customer.v1.GetCustomerResponse")
    public GetCustomerResponseMsg getCustomer(
        @WebParam(name = "getCustomerRequestMsg", targetNamespace = "http://telekom.si/services/common/customer/v1")
        GetCustomerRequestMsg getCustomerRequestMsg)
        throws CustomerServiceException
    ;

    /**
     * 
     * @param getSystemInfoRequestMsg
     * @return
     *     returns si.telekom.services.common.base.v1.GetSystemInfoResponseMsg
     */
    @WebMethod(action = "http://telekom.si/services/common/base/v1/getSystemInfo")
    @WebResult(name = "getSystemInfoResponseMsg", targetNamespace = "http://telekom.si/services/common/base/v1")
    @RequestWrapper(localName = "getSystemInfo", targetNamespace = "http://telekom.si/services/common/base/v1", className = "si.telekom.services.common.base.v1.GetSystemInfo")
    @ResponseWrapper(localName = "getSystemInfoResponse", targetNamespace = "http://telekom.si/services/common/base/v1", className = "si.telekom.services.common.base.v1.GetSystemInfoResponse")
    public GetSystemInfoResponseMsg getSystemInfo(
        @WebParam(name = "getSystemInfoRequestMsg", targetNamespace = "http://telekom.si/services/common/base/v1")
        GetSystemInfoRequestMsg getSystemInfoRequestMsg);

    /**
     * 
     * @param updateCustomerRequestMsg
     * @return
     *     returns si.telekom.services.common.customer.v1.UpdateCustomerResponseMsg
     * @throws CustomerServiceException
     */
    @WebMethod(action = "http://telekom.si/services/common/customer/v1/updateCustomer")
    @WebResult(name = "updateCustomerResponseMsg", targetNamespace = "http://telekom.si/services/common/customer/v1")
    @RequestWrapper(localName = "updateCustomer", targetNamespace = "http://telekom.si/services/common/customer/v1", className = "si.telekom.services.common.customer.v1.UpdateCustomer")
    @ResponseWrapper(localName = "updateCustomerResponse", targetNamespace = "http://telekom.si/services/common/customer/v1", className = "si.telekom.services.common.customer.v1.UpdateCustomerResponse")
    public UpdateCustomerResponseMsg updateCustomer(
        @WebParam(name = "updateCustomerRequestMsg", targetNamespace = "http://telekom.si/services/common/customer/v1")
        UpdateCustomerRequestMsg updateCustomerRequestMsg)
        throws CustomerServiceException
    ;

}
