
package si.telekom.dis.server.jaxwsClient.catalogService;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "catalogServiceException", targetNamespace = "http://telekom.si/services/common/base/v1")
public class CatalogServiceException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CatalogServiceException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CatalogServiceException_Exception(String message, CatalogServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public CatalogServiceException_Exception(String message, CatalogServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: si.telekom.dis.server.jaxwsClient.catalogService.CatalogServiceException
     */
    public CatalogServiceException getFaultInfo() {
        return faultInfo;
    }

}
