
package si.telekom.dis.server.jaxwsClient.pdfGenerator;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "Exception", targetNamespace = "http://templates.mobitel.com/")
public class Exception_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private si.telekom.dis.server.jaxwsClient.pdfGenerator.Exception faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public Exception_Exception(String message, si.telekom.dis.server.jaxwsClient.pdfGenerator.Exception faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public Exception_Exception(String message, si.telekom.dis.server.jaxwsClient.pdfGenerator.Exception faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: si.telekom.dis.server.jaxwsClient.pdfGenerator.Exception
     */
    public si.telekom.dis.server.jaxwsClient.pdfGenerator.Exception getFaultInfo() {
        return faultInfo;
    }

}
