
package si.telekom.dis.server.jaxwsClient.eRender;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ERenderImplService", targetNamespace = "http://erender.telekom.si/", wsdlLocation = "http://erender-test.ts.telekom.si:8080/PdfGenerator/erenderServices?wsdl")
public class ERenderImplService
    extends Service
{

    private final static URL ERENDERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ERENDERIMPLSERVICE_EXCEPTION;
    private final static QName ERENDERIMPLSERVICE_QNAME = new QName("http://erender.telekom.si/", "ERenderImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://erender-test.ts.telekom.si:8080/PdfGenerator/erenderServices?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ERENDERIMPLSERVICE_WSDL_LOCATION = url;
        ERENDERIMPLSERVICE_EXCEPTION = e;
    }

    public ERenderImplService() {
        super(__getWsdlLocation(), ERENDERIMPLSERVICE_QNAME);
    }

    public ERenderImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ERender
     */
    @WebEndpoint(name = "ERenderImplPort")
    public ERender getERenderImplPort() {
        return super.getPort(new QName("http://erender.telekom.si/", "ERenderImplPort"), ERender.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ERender
     */
    @WebEndpoint(name = "ERenderImplPort")
    public ERender getERenderImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://erender.telekom.si/", "ERenderImplPort"), ERender.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ERENDERIMPLSERVICE_EXCEPTION!= null) {
            throw ERENDERIMPLSERVICE_EXCEPTION;
        }
        return ERENDERIMPLSERVICE_WSDL_LOCATION;
    }

}
