
package si.telekom.dis.server.jaxwsClient.eRender;

import java.util.List;
import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PdfGenerator", targetNamespace = "http://templates.mobitel.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PdfGenerator {


    /**
     * 
     * @param password
     * @param rObjectId
     * @param dctmFormat
     * @param domain
     * @param makeVersion
     * @param osName
     * @param content
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "setContent", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.SetContent")
    @ResponseWrapper(localName = "setContentResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.SetContentResponse")
    public void setContent(
        @WebParam(name = "rObjectId", targetNamespace = "http://templates.mobitel.com/")
        String rObjectId,
        @WebParam(name = "content", targetNamespace = "http://templates.mobitel.com/")
        byte[] content,
        @WebParam(name = "dctmFormat", targetNamespace = "http://templates.mobitel.com/")
        String dctmFormat,
        @WebParam(name = "makeVersion", targetNamespace = "http://templates.mobitel.com/")
        boolean makeVersion,
        @WebParam(name = "osName", targetNamespace = "http://templates.mobitel.com/")
        String osName,
        @WebParam(name = "domain", targetNamespace = "http://templates.mobitel.com/")
        String domain,
        @WebParam(name = "password", targetNamespace = "http://templates.mobitel.com/")
        String password)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<si.telekom.dis.server.jaxwsClient.eRender.Format>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://templates.mobitel.com/")
    @RequestWrapper(localName = "getRenditions", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetRenditions")
    @ResponseWrapper(localName = "getRenditionsResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetRenditionsResponse")
    public List<Format> getRenditions(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4)
        throws Exception_Exception
    ;

    /**
     * 
     * @param docbaseName
     * @param password
     * @param documentumFormat
     * @param rObjectId
     * @param data
     * @param domain
     * @param osName
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "addRendition", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.AddRendition")
    @ResponseWrapper(localName = "addRenditionResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.AddRenditionResponse")
    public void addRendition(
        @WebParam(name = "rObjectId", targetNamespace = "http://templates.mobitel.com/")
        String rObjectId,
        @WebParam(name = "osName", targetNamespace = "http://templates.mobitel.com/")
        String osName,
        @WebParam(name = "domain", targetNamespace = "http://templates.mobitel.com/")
        String domain,
        @WebParam(name = "password", targetNamespace = "http://templates.mobitel.com/")
        String password,
        @WebParam(name = "docbaseName", targetNamespace = "http://templates.mobitel.com/")
        String docbaseName,
        @WebParam(name = "data", targetNamespace = "http://templates.mobitel.com/")
        byte[] data,
        @WebParam(name = "documentumFormat", targetNamespace = "http://templates.mobitel.com/")
        String documentumFormat)
        throws Exception_Exception
    ;

    /**
     * 
     * @param password
     * @param documentumFormat
     * @param data
     * @param domain
     * @param objectName
     * @param osName
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "checkin", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.Checkin")
    @ResponseWrapper(localName = "checkinResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.CheckinResponse")
    public void checkin(
        @WebParam(name = "object_name", targetNamespace = "http://templates.mobitel.com/")
        String objectName,
        @WebParam(name = "osName", targetNamespace = "http://templates.mobitel.com/")
        String osName,
        @WebParam(name = "domain", targetNamespace = "http://templates.mobitel.com/")
        String domain,
        @WebParam(name = "password", targetNamespace = "http://templates.mobitel.com/")
        String password,
        @WebParam(name = "data", targetNamespace = "http://templates.mobitel.com/")
        byte[] data,
        @WebParam(name = "documentumFormat", targetNamespace = "http://templates.mobitel.com/")
        String documentumFormat)
        throws Exception_Exception
    ;

    /**
     * 
     * @param template
     * @param hashMapWrapper
     * @param stringByRef
     * @param id
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://templates.mobitel.com/")
    @RequestWrapper(localName = "getOOPdf", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetOOPdf")
    @ResponseWrapper(localName = "getOOPdfResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetOOPdfResponse")
    public byte[] getOOPdf(
        @WebParam(name = "template", targetNamespace = "http://templates.mobitel.com/")
        Template template,
        @WebParam(name = "id", targetNamespace = "")
        Integer id,
        @WebParam(name = "stringByRef", targetNamespace = "http://templates.mobitel.com/")
        StringByRef stringByRef,
        @WebParam(name = "hashMapWrapper", targetNamespace = "http://templates.mobitel.com/")
        HashMapWrapper hashMapWrapper)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPdf", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetPdf")
    @ResponseWrapper(localName = "getPdfResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetPdfResponse")
    public byte[] getPdf(
        @WebParam(name = "arg0", targetNamespace = "http://templates.mobitel.com/")
        Integer arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<byte[]>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPdfMultiple", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetPdfMultiple")
    @ResponseWrapper(localName = "getPdfMultipleResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetPdfMultipleResponse")
    public List<byte[]> getPdfMultiple(
        @WebParam(name = "arg0", targetNamespace = "http://templates.mobitel.com/")
        Integer arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPdfNew", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetPdfNew")
    @ResponseWrapper(localName = "getPdfNewResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetPdfNewResponse")
    public byte[] getPdfNew(
        @WebParam(name = "arg0", targetNamespace = "http://templates.mobitel.com/")
        Integer arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<byte[]>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPdfMultipleNew", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetPdfMultipleNew")
    @ResponseWrapper(localName = "getPdfMultipleNewResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetPdfMultipleNewResponse")
    public List<byte[]> getPdfMultipleNew(
        @WebParam(name = "arg0", targetNamespace = "http://templates.mobitel.com/")
        Integer arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param id
     * @param barcodes
     * @return
     *     returns java.util.List<byte[]>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPdfMultipleNewWithBarcodes", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetPdfMultipleNewWithBarcodes")
    @ResponseWrapper(localName = "getPdfMultipleNewWithBarcodesResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetPdfMultipleNewWithBarcodesResponse")
    public List<byte[]> getPdfMultipleNewWithBarcodes(
        @WebParam(name = "id", targetNamespace = "http://templates.mobitel.com/")
        Integer id,
        @WebParam(name = "barcodes", targetNamespace = "http://templates.mobitel.com/", mode = WebParam.Mode.INOUT)
        Holder<List<String>> barcodes)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPdfFromOOTemplate", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetPdfFromOOTemplate")
    @ResponseWrapper(localName = "getPdfFromOOTemplateResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetPdfFromOOTemplateResponse")
    public byte[] getPdfFromOOTemplate(
        @WebParam(name = "arg0", targetNamespace = "")
        byte[] arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param docbaseName
     * @param userPassword
     * @param versionLabel
     * @param objectName
     * @param userLoginName
     * @param userDomain
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "pdfBase64Encoded", targetNamespace = "")
    @RequestWrapper(localName = "getTemplateByObjectName", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetTemplateByObjectName")
    @ResponseWrapper(localName = "getTemplateByObjectNameResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetTemplateByObjectNameResponse")
    public byte[] getTemplateByObjectName(
        @WebParam(name = "objectName", targetNamespace = "http://templates.mobitel.com/")
        String objectName,
        @WebParam(name = "versionLabel", targetNamespace = "http://templates.mobitel.com/")
        String versionLabel,
        @WebParam(name = "docbaseName", targetNamespace = "http://templates.mobitel.com/")
        String docbaseName,
        @WebParam(name = "userLoginName", targetNamespace = "http://templates.mobitel.com/")
        String userLoginName,
        @WebParam(name = "userDomain", targetNamespace = "http://templates.mobitel.com/")
        String userDomain,
        @WebParam(name = "userPassword", targetNamespace = "http://templates.mobitel.com/")
        String userPassword)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<si.telekom.dis.server.jaxwsClient.eRender.Template>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTemplateList", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetTemplateList")
    @ResponseWrapper(localName = "getTemplateListResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetTemplateListResponse")
    public List<Template> getTemplateList(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4)
        throws Exception_Exception
    ;

    /**
     * 
     * @param sql
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://templates.mobitel.com/")
    @RequestWrapper(localName = "evaluateSql", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.EvaluateSql")
    @ResponseWrapper(localName = "evaluateSqlResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.EvaluateSqlResponse")
    public String evaluateSql(
        @WebParam(name = "sql", targetNamespace = "http://templates.mobitel.com/")
        String sql)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg7
     * @param arg6
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "setTemplateData", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.SetTemplateData")
    @ResponseWrapper(localName = "setTemplateDataResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.SetTemplateDataResponse")
    public void setTemplateData(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        List<String> arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7)
        throws Exception_Exception
    ;

    /**
     * 
     * @param password
     * @param documentumFormat
     * @param data
     * @param keepRenditions
     * @param domain
     * @param objectName
     * @param osName
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "checkinTemplate", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.CheckinTemplate")
    @ResponseWrapper(localName = "checkinTemplateResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.CheckinTemplateResponse")
    public void checkinTemplate(
        @WebParam(name = "object_name", targetNamespace = "http://templates.mobitel.com/")
        String objectName,
        @WebParam(name = "osName", targetNamespace = "http://templates.mobitel.com/")
        String osName,
        @WebParam(name = "domain", targetNamespace = "http://templates.mobitel.com/")
        String domain,
        @WebParam(name = "password", targetNamespace = "http://templates.mobitel.com/")
        String password,
        @WebParam(name = "data", targetNamespace = "http://templates.mobitel.com/")
        byte[] data,
        @WebParam(name = "documentumFormat", targetNamespace = "http://templates.mobitel.com/")
        String documentumFormat,
        @WebParam(name = "keepRenditions", targetNamespace = "http://templates.mobitel.com/")
        Boolean keepRenditions)
        throws Exception_Exception
    ;

    /**
     * 
     * @param password
     * @param documentumFormat
     * @param data
     * @param keepRenditions
     * @param domain
     * @param language
     * @param templateId
     * @param osName
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "checkinTemplateByTemplateId", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.CheckinTemplateByTemplateId")
    @ResponseWrapper(localName = "checkinTemplateByTemplateIdResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.CheckinTemplateByTemplateIdResponse")
    public void checkinTemplateByTemplateId(
        @WebParam(name = "templateId", targetNamespace = "http://templates.mobitel.com/")
        String templateId,
        @WebParam(name = "language", targetNamespace = "http://templates.mobitel.com/")
        String language,
        @WebParam(name = "osName", targetNamespace = "http://templates.mobitel.com/")
        String osName,
        @WebParam(name = "domain", targetNamespace = "http://templates.mobitel.com/")
        String domain,
        @WebParam(name = "password", targetNamespace = "http://templates.mobitel.com/")
        String password,
        @WebParam(name = "data", targetNamespace = "http://templates.mobitel.com/")
        byte[] data,
        @WebParam(name = "documentumFormat", targetNamespace = "http://templates.mobitel.com/")
        String documentumFormat,
        @WebParam(name = "keepRenditions", targetNamespace = "http://templates.mobitel.com/")
        Boolean keepRenditions)
        throws Exception_Exception
    ;

    /**
     * 
     * @param docbaseName
     * @param password
     * @param documentumFormat
     * @param rObjectId
     * @param data
     * @param domain
     * @param osName
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "checkinMinor", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.CheckinMinor")
    @ResponseWrapper(localName = "checkinMinorResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.CheckinMinorResponse")
    public void checkinMinor(
        @WebParam(name = "rObjectId", targetNamespace = "http://templates.mobitel.com/")
        String rObjectId,
        @WebParam(name = "osName", targetNamespace = "http://templates.mobitel.com/")
        String osName,
        @WebParam(name = "domain", targetNamespace = "http://templates.mobitel.com/")
        String domain,
        @WebParam(name = "password", targetNamespace = "http://templates.mobitel.com/")
        String password,
        @WebParam(name = "docbaseName", targetNamespace = "http://templates.mobitel.com/")
        String docbaseName,
        @WebParam(name = "data", targetNamespace = "http://templates.mobitel.com/")
        byte[] data,
        @WebParam(name = "documentumFormat", targetNamespace = "http://templates.mobitel.com/")
        String documentumFormat)
        throws Exception_Exception
    ;

    /**
     * 
     * @param docbaseName
     * @param password
     * @param documentumFormat
     * @param rObjectId
     * @param data
     * @param domain
     * @param osName
     * @param versionNumber
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "checkinMinorAndSetVersion", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.CheckinMinorAndSetVersion")
    @ResponseWrapper(localName = "checkinMinorAndSetVersionResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.CheckinMinorAndSetVersionResponse")
    public void checkinMinorAndSetVersion(
        @WebParam(name = "rObjectId", targetNamespace = "http://templates.mobitel.com/")
        String rObjectId,
        @WebParam(name = "versionNumber", targetNamespace = "http://templates.mobitel.com/")
        String versionNumber,
        @WebParam(name = "osName", targetNamespace = "http://templates.mobitel.com/")
        String osName,
        @WebParam(name = "domain", targetNamespace = "http://templates.mobitel.com/")
        String domain,
        @WebParam(name = "password", targetNamespace = "http://templates.mobitel.com/")
        String password,
        @WebParam(name = "docbaseName", targetNamespace = "http://templates.mobitel.com/")
        String docbaseName,
        @WebParam(name = "data", targetNamespace = "http://templates.mobitel.com/")
        byte[] data,
        @WebParam(name = "documentumFormat", targetNamespace = "http://templates.mobitel.com/")
        String documentumFormat)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "unLock", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.UnLock")
    @ResponseWrapper(localName = "unLockResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.UnLockResponse")
    public void unLock(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns si.telekom.dis.server.jaxwsClient.eRender.DctmAttribute
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://templates.mobitel.com/")
    @RequestWrapper(localName = "getDctmAttribute", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetDctmAttribute")
    @ResponseWrapper(localName = "getDctmAttributeResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetDctmAttributeResponse")
    public DctmAttribute getDctmAttribute(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3)
        throws Exception_Exception
    ;

    /**
     * 
     * @param docBase
     * @param password
     * @param rObjectId
     * @param domain
     * @param objectName
     * @param osName
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "newBarcode", targetNamespace = "http://templates.mobitel.com/")
    @RequestWrapper(localName = "duplicateDctmObject", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.DuplicateDctmObject")
    @ResponseWrapper(localName = "duplicateDctmObjectResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.DuplicateDctmObjectResponse")
    public String duplicateDctmObject(
        @WebParam(name = "rObjectId", targetNamespace = "http://templates.mobitel.com/")
        String rObjectId,
        @WebParam(name = "docBase", targetNamespace = "http://templates.mobitel.com/")
        String docBase,
        @WebParam(name = "objectName", targetNamespace = "http://templates.mobitel.com/")
        String objectName,
        @WebParam(name = "osName", targetNamespace = "http://templates.mobitel.com/")
        String osName,
        @WebParam(name = "domain", targetNamespace = "http://templates.mobitel.com/")
        String domain,
        @WebParam(name = "password", targetNamespace = "http://templates.mobitel.com/")
        String password)
        throws Exception_Exception
    ;

    /**
     * 
     * @param docBase
     * @param password
     * @param rObjectId
     * @param domain
     * @param osName
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteDctmObject", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.DeleteDctmObject")
    @ResponseWrapper(localName = "deleteDctmObjectResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.DeleteDctmObjectResponse")
    public void deleteDctmObject(
        @WebParam(name = "rObjectId", targetNamespace = "http://templates.mobitel.com/")
        String rObjectId,
        @WebParam(name = "docBase", targetNamespace = "http://templates.mobitel.com/")
        String docBase,
        @WebParam(name = "osName", targetNamespace = "http://templates.mobitel.com/")
        String osName,
        @WebParam(name = "domain", targetNamespace = "http://templates.mobitel.com/")
        String domain,
        @WebParam(name = "password", targetNamespace = "http://templates.mobitel.com/")
        String password)
        throws Exception_Exception
    ;

    /**
     * 
     * @param docBase
     * @param password
     * @param documentumFormat
     * @param data
     * @param domain
     * @param osName
     * @param objectType
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://templates.mobitel.com/")
    @RequestWrapper(localName = "createDctmObjectMTOM", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.CreateDctmObjectMTOM")
    @ResponseWrapper(localName = "createDctmObjectMTOMResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.CreateDctmObjectMTOMResponse")
    public String createDctmObjectMTOM(
        @WebParam(name = "objectType", targetNamespace = "http://templates.mobitel.com/")
        String objectType,
        @WebParam(name = "data", targetNamespace = "http://templates.mobitel.com/")
        byte[] data,
        @WebParam(name = "documentumFormat", targetNamespace = "http://templates.mobitel.com/")
        String documentumFormat,
        @WebParam(name = "docBase", targetNamespace = "http://templates.mobitel.com/")
        String docBase,
        @WebParam(name = "osName", targetNamespace = "http://templates.mobitel.com/")
        String osName,
        @WebParam(name = "domain", targetNamespace = "http://templates.mobitel.com/")
        String domain,
        @WebParam(name = "password", targetNamespace = "http://templates.mobitel.com/")
        String password)
        throws Exception_Exception
    ;

    /**
     * 
     * @param docBase
     * @param password
     * @param documentumFormat
     * @param domain
     * @param osName
     * @param content
     * @param objectType
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://templates.mobitel.com/")
    @RequestWrapper(localName = "createDctmObject", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.CreateDctmObject")
    @ResponseWrapper(localName = "createDctmObjectResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.CreateDctmObjectResponse")
    public String createDctmObject(
        @WebParam(name = "objectType", targetNamespace = "http://templates.mobitel.com/")
        String objectType,
        @WebParam(name = "content", targetNamespace = "http://templates.mobitel.com/")
        byte[] content,
        @WebParam(name = "documentumFormat", targetNamespace = "http://templates.mobitel.com/")
        String documentumFormat,
        @WebParam(name = "docBase", targetNamespace = "http://templates.mobitel.com/")
        String docBase,
        @WebParam(name = "osName", targetNamespace = "http://templates.mobitel.com/")
        String osName,
        @WebParam(name = "domain", targetNamespace = "http://templates.mobitel.com/")
        String domain,
        @WebParam(name = "password", targetNamespace = "http://templates.mobitel.com/")
        String password)
        throws Exception_Exception
    ;

    /**
     * 
     * @param password
     * @param docBase
     * @param domain
     * @param osName
     * @return
     *     returns java.util.List<si.telekom.dis.server.jaxwsClient.eRender.DctmQuery>
     */
    @WebMethod
    @WebResult(targetNamespace = "http://templates.mobitel.com/")
    @RequestWrapper(localName = "getDctmQueries", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetDctmQueries")
    @ResponseWrapper(localName = "getDctmQueriesResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetDctmQueriesResponse")
    public List<DctmQuery> getDctmQueries(
        @WebParam(name = "osName", targetNamespace = "http://templates.mobitel.com/")
        String osName,
        @WebParam(name = "domain", targetNamespace = "http://templates.mobitel.com/")
        String domain,
        @WebParam(name = "password", targetNamespace = "http://templates.mobitel.com/")
        String password,
        @WebParam(name = "docBase", targetNamespace = "http://templates.mobitel.com/")
        String docBase);

    /**
     * 
     * @param docbaseName
     * @param password
     * @param groupName
     * @param domain
     * @param osName
     * @param username
     * @return
     *     returns java.lang.Boolean
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://templates.mobitel.com/")
    @RequestWrapper(localName = "isUserMember", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.IsUserMember")
    @ResponseWrapper(localName = "isUserMemberResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.IsUserMemberResponse")
    public Boolean isUserMember(
        @WebParam(name = "osName", targetNamespace = "http://templates.mobitel.com/")
        String osName,
        @WebParam(name = "domain", targetNamespace = "http://templates.mobitel.com/")
        String domain,
        @WebParam(name = "password", targetNamespace = "http://templates.mobitel.com/")
        String password,
        @WebParam(name = "docbaseName", targetNamespace = "http://templates.mobitel.com/")
        String docbaseName,
        @WebParam(name = "username", targetNamespace = "http://templates.mobitel.com/")
        String username,
        @WebParam(name = "groupName", targetNamespace = "http://templates.mobitel.com/")
        String groupName)
        throws Exception_Exception
    ;

    /**
     * 
     * @param pasword
     * @param docbaseName
     * @param domain
     * @param dosExtension
     * @param osName
     * @return
     *     returns java.util.List<si.telekom.dis.server.jaxwsClient.eRender.Format>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "formats", targetNamespace = "http://templates.mobitel.com/")
    @RequestWrapper(localName = "getFormatsFromDosExtension", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetFormatsFromDosExtension")
    @ResponseWrapper(localName = "getFormatsFromDosExtensionResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetFormatsFromDosExtensionResponse")
    public List<Format> getFormatsFromDosExtension(
        @WebParam(name = "dosExtension", targetNamespace = "http://templates.mobitel.com/")
        String dosExtension,
        @WebParam(name = "osName", targetNamespace = "http://templates.mobitel.com/")
        String osName,
        @WebParam(name = "domain", targetNamespace = "http://templates.mobitel.com/")
        String domain,
        @WebParam(name = "pasword", targetNamespace = "http://templates.mobitel.com/")
        String pasword,
        @WebParam(name = "docbaseName", targetNamespace = "http://templates.mobitel.com/")
        String docbaseName)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "concatTwoPdfs", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.ConcatTwoPdfs")
    @ResponseWrapper(localName = "concatTwoPdfsResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.ConcatTwoPdfsResponse")
    public byte[] concatTwoPdfs(
        @WebParam(name = "arg0", targetNamespace = "")
        byte[] arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        byte[] arg1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param template
     * @param result
     * @param hashMapWrapper
     * @param stringByRef
     * @param id
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "getOpenOfficePdf", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetOpenOfficePdf")
    @ResponseWrapper(localName = "getOpenOfficePdfResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetOpenOfficePdfResponse")
    public void getOpenOfficePdf(
        @WebParam(name = "template", targetNamespace = "http://templates.mobitel.com/")
        Template template,
        @WebParam(name = "id", targetNamespace = "")
        Integer id,
        @WebParam(name = "stringByRef", targetNamespace = "http://templates.mobitel.com/", mode = WebParam.Mode.INOUT)
        Holder<StringByRef> stringByRef,
        @WebParam(name = "hashMapWrapper", targetNamespace = "http://templates.mobitel.com/")
        HashMapWrapper hashMapWrapper,
        @WebParam(name = "result", targetNamespace = "http://templates.mobitel.com/", mode = WebParam.Mode.OUT)
        Holder<byte[]> result)
        throws Exception_Exception
    ;

    /**
     * 
     * @param loginName
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserDomain", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetUserDomain")
    @ResponseWrapper(localName = "getUserDomainResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetUserDomainResponse")
    public String getUserDomain(
        @WebParam(name = "loginName", targetNamespace = "http://templates.mobitel.com/")
        String loginName)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg6
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "setAttributeTo", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.SetAttributeTo")
    @ResponseWrapper(localName = "setAttributeToResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.SetAttributeToResponse")
    public void setAttributeTo(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6)
        throws Exception_Exception
    ;

    /**
     * 
     * @param paramValues
     * @param templateTypeId
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOpenOfficePdfForHashMap", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetOpenOfficePdfForHashMap")
    @ResponseWrapper(localName = "getOpenOfficePdfForHashMapResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetOpenOfficePdfForHashMapResponse")
    public byte[] getOpenOfficePdfForHashMap(
        @WebParam(name = "templateTypeId", targetNamespace = "http://templates.mobitel.com/")
        Integer templateTypeId,
        @WebParam(name = "paramValues", targetNamespace = "http://templates.mobitel.com/")
        HashMapWrapper paramValues)
        throws Exception_Exception
    ;

    /**
     * 
     * @param typeId
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://templates.mobitel.com/")
    @RequestWrapper(localName = "getTemplateFields", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetTemplateFields")
    @ResponseWrapper(localName = "getTemplateFieldsResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetTemplateFieldsResponse")
    public List<String> getTemplateFields(
        @WebParam(name = "typeId", targetNamespace = "http://templates.mobitel.com/")
        int typeId)
        throws Exception_Exception
    ;

    /**
     * 
     * @param typeId
     * @return
     *     returns si.telekom.dis.server.jaxwsClient.eRender.Template
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "http://templates.mobitel.com/")
    @RequestWrapper(localName = "getTemplateByTemplateId", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetTemplateByTemplateId")
    @ResponseWrapper(localName = "getTemplateByTemplateIdResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetTemplateByTemplateIdResponse")
    public Template getTemplateByTemplateId(
        @WebParam(name = "typeId", targetNamespace = "http://templates.mobitel.com/")
        int typeId)
        throws Exception_Exception
    ;

    /**
     * 
     * @param accessorName
     * @param password
     * @param docBase
     * @param domain
     * @param rObjectIds
     * @param osName
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "revoke", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.Revoke")
    @ResponseWrapper(localName = "revokeResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.RevokeResponse")
    public void revoke(
        @WebParam(name = "rObjectIds", targetNamespace = "http://templates.mobitel.com/")
        List<String> rObjectIds,
        @WebParam(name = "accessorName", targetNamespace = "http://templates.mobitel.com/")
        String accessorName,
        @WebParam(name = "osName", targetNamespace = "http://templates.mobitel.com/")
        String osName,
        @WebParam(name = "password", targetNamespace = "http://templates.mobitel.com/")
        String password,
        @WebParam(name = "domain", targetNamespace = "http://templates.mobitel.com/")
        String domain,
        @WebParam(name = "docBase", targetNamespace = "http://templates.mobitel.com/")
        String docBase)
        throws Exception_Exception
    ;

    /**
     * 
     * @param typeId
     * @param keyValues
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPdfNewFromKeyValues", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetPdfNewFromKeyValues")
    @ResponseWrapper(localName = "getPdfNewFromKeyValuesResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetPdfNewFromKeyValuesResponse")
    public byte[] getPdfNewFromKeyValues(
        @WebParam(name = "typeId", targetNamespace = "http://templates.mobitel.com/")
        Integer typeId,
        @WebParam(name = "keyValues", targetNamespace = "http://templates.mobitel.com/")
        List<KeyValue> keyValues)
        throws Exception_Exception
    ;

    /**
     * 
     * @param docBase
     * @param password
     * @param rObjectId
     * @param domain
     * @param label
     * @param osName
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "removeVersionLabel", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.RemoveVersionLabel")
    @ResponseWrapper(localName = "removeVersionLabelResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.RemoveVersionLabelResponse")
    public void removeVersionLabel(
        @WebParam(name = "rObjectId", targetNamespace = "http://templates.mobitel.com/")
        String rObjectId,
        @WebParam(name = "docBase", targetNamespace = "http://templates.mobitel.com/")
        String docBase,
        @WebParam(name = "label", targetNamespace = "http://templates.mobitel.com/")
        String label,
        @WebParam(name = "osName", targetNamespace = "http://templates.mobitel.com/")
        String osName,
        @WebParam(name = "domain", targetNamespace = "http://templates.mobitel.com/")
        String domain,
        @WebParam(name = "password", targetNamespace = "http://templates.mobitel.com/")
        String password)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "replaceVersionLabel", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.ReplaceVersionLabel")
    @ResponseWrapper(localName = "replaceVersionLabelResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.ReplaceVersionLabelResponse")
    public void replaceVersionLabel(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5)
        throws Exception_Exception
    ;

    /**
     * 
     * @param docBase
     * @param password
     * @param rObjectId
     * @param domain
     * @param label
     * @param osName
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "addVersionLabel", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.AddVersionLabel")
    @ResponseWrapper(localName = "addVersionLabelResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.AddVersionLabelResponse")
    public void addVersionLabel(
        @WebParam(name = "rObjectId", targetNamespace = "http://templates.mobitel.com/")
        String rObjectId,
        @WebParam(name = "docBase", targetNamespace = "http://templates.mobitel.com/")
        String docBase,
        @WebParam(name = "label", targetNamespace = "http://templates.mobitel.com/")
        String label,
        @WebParam(name = "osName", targetNamespace = "http://templates.mobitel.com/")
        String osName,
        @WebParam(name = "domain", targetNamespace = "http://templates.mobitel.com/")
        String domain,
        @WebParam(name = "password", targetNamespace = "http://templates.mobitel.com/")
        String password)
        throws Exception_Exception
    ;

    /**
     * 
     * @param deleteOnlyCurrent
     * @param docBase
     * @param password
     * @param domain
     * @param rObjectIds
     * @param osName
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteDctmObjects", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.DeleteDctmObjects")
    @ResponseWrapper(localName = "deleteDctmObjectsResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.DeleteDctmObjectsResponse")
    public void deleteDctmObjects(
        @WebParam(name = "rObjectIds", targetNamespace = "http://templates.mobitel.com/")
        List<String> rObjectIds,
        @WebParam(name = "deleteOnlyCurrent", targetNamespace = "http://templates.mobitel.com/")
        boolean deleteOnlyCurrent,
        @WebParam(name = "docBase", targetNamespace = "http://templates.mobitel.com/")
        String docBase,
        @WebParam(name = "osName", targetNamespace = "http://templates.mobitel.com/")
        String osName,
        @WebParam(name = "domain", targetNamespace = "http://templates.mobitel.com/")
        String domain,
        @WebParam(name = "password", targetNamespace = "http://templates.mobitel.com/")
        String password)
        throws Exception_Exception
    ;

    /**
     * 
     * @param password
     * @param domain
     * @param barcodes
     * @param inetids
     * @param osName
     */
    @WebMethod
    @RequestWrapper(localName = "generatePdfAndRaiseMinorVersion", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GeneratePdfAndRaiseMinorVersion")
    @ResponseWrapper(localName = "generatePdfAndRaiseMinorVersionResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GeneratePdfAndRaiseMinorVersionResponse")
    public void generatePdfAndRaiseMinorVersion(
        @WebParam(name = "barcodes", targetNamespace = "http://erender.telekom.com")
        List<String> barcodes,
        @WebParam(name = "inetids", targetNamespace = "http://erender.telekom.com")
        List<String> inetids,
        @WebParam(name = "osName", targetNamespace = "http://templates.mobitel.com")
        String osName,
        @WebParam(name = "domain", targetNamespace = "http://templates.mobitel.com")
        String domain,
        @WebParam(name = "password", targetNamespace = "http://templates.mobitel.com")
        String password);

    /**
     * 
     * @param smartlistRObjectId
     * @param password
     * @param docbase
     * @param pageIndex
     * @param domain
     * @param pageMaxRowCount
     * @param osName
     * @return
     *     returns si.telekom.dis.server.jaxwsClient.eRender.QueryResult
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "http://templates.mobitel.com/")
    @RequestWrapper(localName = "runSmartList", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.RunSmartList")
    @ResponseWrapper(localName = "runSmartListResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.RunSmartListResponse")
    public QueryResult runSmartList(
        @WebParam(name = "smartlistRObjectId", targetNamespace = "http://templates.mobitel.com/")
        String smartlistRObjectId,
        @WebParam(name = "docbase", targetNamespace = "http://templates.mobitel.com/")
        String docbase,
        @WebParam(name = "pageIndex", targetNamespace = "http://templates.mobitel.com/")
        int pageIndex,
        @WebParam(name = "pageMaxRowCount", targetNamespace = "http://templates.mobitel.com/")
        int pageMaxRowCount,
        @WebParam(name = "osName", targetNamespace = "http://templates.mobitel.com/")
        String osName,
        @WebParam(name = "domain", targetNamespace = "http://templates.mobitel.com/")
        String domain,
        @WebParam(name = "password", targetNamespace = "http://templates.mobitel.com/")
        String password);

    /**
     * 
     * @param docBase
     * @param password
     * @param domain
     * @param rObjectIds
     * @param osName
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "transferDctmObjectsToDev", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.TransferDctmObjectsToDev")
    @ResponseWrapper(localName = "transferDctmObjectsToDevResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.TransferDctmObjectsToDevResponse")
    public void transferDctmObjectsToDev(
        @WebParam(name = "rObjectIds", targetNamespace = "http://templates.mobitel.com/")
        List<String> rObjectIds,
        @WebParam(name = "docBase", targetNamespace = "http://templates.mobitel.com/")
        String docBase,
        @WebParam(name = "osName", targetNamespace = "http://templates.mobitel.com/")
        String osName,
        @WebParam(name = "domain", targetNamespace = "http://templates.mobitel.com/")
        String domain,
        @WebParam(name = "password", targetNamespace = "http://templates.mobitel.com/")
        String password)
        throws Exception_Exception
    ;

    /**
     * 
     * @param docBase
     * @param password
     * @param domain
     * @param rObjectIds
     * @param osName
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "transferDctmObjectsToTest", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.TransferDctmObjectsToTest")
    @ResponseWrapper(localName = "transferDctmObjectsToTestResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.TransferDctmObjectsToTestResponse")
    public void transferDctmObjectsToTest(
        @WebParam(name = "rObjectIds", targetNamespace = "http://templates.mobitel.com/")
        List<String> rObjectIds,
        @WebParam(name = "docBase", targetNamespace = "http://templates.mobitel.com/")
        String docBase,
        @WebParam(name = "osName", targetNamespace = "http://templates.mobitel.com/")
        String osName,
        @WebParam(name = "domain", targetNamespace = "http://templates.mobitel.com/")
        String domain,
        @WebParam(name = "password", targetNamespace = "http://templates.mobitel.com/")
        String password)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<si.telekom.dis.server.jaxwsClient.eRender.ArrayList>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "syncAtts", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.SyncAtts")
    @ResponseWrapper(localName = "syncAttsResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.SyncAttsResponse")
    public List<ArrayList> syncAtts(
        @WebParam(name = "arg0", targetNamespace = "")
        boolean arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAtts", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetAtts")
    @ResponseWrapper(localName = "getAttsResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetAttsResponse")
    public List<String> getAtts(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "syncTemplate", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.SyncTemplate")
    @ResponseWrapper(localName = "syncTemplateResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.SyncTemplateResponse")
    public List<String> syncTemplate(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "configureERender", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.ConfigureERender")
    @ResponseWrapper(localName = "configureERenderResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.ConfigureERenderResponse")
    public void configureERender(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param accessorName
     * @param password
     * @param docBase
     * @param basicPermit
     * @param extPermit
     * @param domain
     * @param rObjectIds
     * @param osName
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "grant", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.Grant")
    @ResponseWrapper(localName = "grantResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GrantResponse")
    public void grant(
        @WebParam(name = "rObjectIds", targetNamespace = "http://templates.mobitel.com/")
        List<String> rObjectIds,
        @WebParam(name = "accessorName", targetNamespace = "http://templates.mobitel.com/")
        String accessorName,
        @WebParam(name = "basicPermit", targetNamespace = "http://templates.mobitel.com/")
        int basicPermit,
        @WebParam(name = "extPermit", targetNamespace = "http://templates.mobitel.com/")
        String extPermit,
        @WebParam(name = "osName", targetNamespace = "http://templates.mobitel.com/")
        String osName,
        @WebParam(name = "password", targetNamespace = "http://templates.mobitel.com/")
        String password,
        @WebParam(name = "domain", targetNamespace = "http://templates.mobitel.com/")
        String domain,
        @WebParam(name = "docBase", targetNamespace = "http://templates.mobitel.com/")
        String docBase)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg7
     * @param arg6
     * @return
     *     returns javax.activation.DataHandler
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getContents", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetContents")
    @ResponseWrapper(localName = "getContentsResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetContentsResponse")
    public DataHandler getContents(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<String> arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        Boolean arg7)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "lock", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.Lock")
    @ResponseWrapper(localName = "lockResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.LockResponse")
    public void lock(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4)
        throws Exception_Exception
    ;

    /**
     * 
     * @param password
     * @param docbase
     * @param dqlQuery
     * @param pageIndex
     * @param domain
     * @param pageMaxRowCount
     * @param osName
     * @return
     *     returns si.telekom.dis.server.jaxwsClient.eRender.QueryResult
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "http://templates.mobitel.com/")
    @RequestWrapper(localName = "query", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.Query")
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.QueryResponse")
    public QueryResult query(
        @WebParam(name = "dqlQuery", targetNamespace = "http://templates.mobitel.com/")
        String dqlQuery,
        @WebParam(name = "docbase", targetNamespace = "http://templates.mobitel.com/")
        String docbase,
        @WebParam(name = "pageIndex", targetNamespace = "http://templates.mobitel.com/")
        int pageIndex,
        @WebParam(name = "pageMaxRowCount", targetNamespace = "http://templates.mobitel.com/")
        int pageMaxRowCount,
        @WebParam(name = "osName", targetNamespace = "http://templates.mobitel.com/")
        String osName,
        @WebParam(name = "domain", targetNamespace = "http://templates.mobitel.com/")
        String domain,
        @WebParam(name = "password", targetNamespace = "http://templates.mobitel.com/")
        String password)
        throws Exception_Exception
    ;

    /**
     * 
     * @param docBase
     * @param password
     * @param rObjectId
     * @param dctmFormat
     * @param domain
     * @param osName
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "http://templates.mobitel.com/")
    @RequestWrapper(localName = "getContent", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetContent")
    @ResponseWrapper(localName = "getContentResponse", targetNamespace = "http://templates.mobitel.com/", className = "si.telekom.dis.server.jaxwsClient.eRender.GetContentResponse")
    public byte[] getContent(
        @WebParam(name = "rObjectId", targetNamespace = "http://templates.mobitel.com/")
        String rObjectId,
        @WebParam(name = "docBase", targetNamespace = "http://templates.mobitel.com/")
        String docBase,
        @WebParam(name = "dctmFormat", targetNamespace = "http://templates.mobitel.com/")
        String dctmFormat,
        @WebParam(name = "osName", targetNamespace = "http://templates.mobitel.com/")
        String osName,
        @WebParam(name = "domain", targetNamespace = "http://templates.mobitel.com/")
        String domain,
        @WebParam(name = "password", targetNamespace = "http://templates.mobitel.com/")
        String password)
        throws Exception_Exception
    ;

}
