
package si.telekom.dis.server.jaxwsClient.eRender;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PdfGeneratorImplService", targetNamespace = "http://templates.mobitel.com/", wsdlLocation = "http://erender-test.ts.telekom.si:8080/PdfGenerator/services?wsdl")
public class PdfGeneratorImplService
    extends Service
{

    private final static URL PDFGENERATORIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PDFGENERATORIMPLSERVICE_EXCEPTION;
    private final static QName PDFGENERATORIMPLSERVICE_QNAME = new QName("http://templates.mobitel.com/", "PdfGeneratorImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://erender-test.ts.telekom.si:8080/PdfGenerator/services?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PDFGENERATORIMPLSERVICE_WSDL_LOCATION = url;
        PDFGENERATORIMPLSERVICE_EXCEPTION = e;
    }

    public PdfGeneratorImplService() {
        super(__getWsdlLocation(), PDFGENERATORIMPLSERVICE_QNAME);
    }

    public PdfGeneratorImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns PdfGenerator
     */
    @WebEndpoint(name = "PdfGeneratorImplPort")
    public PdfGenerator getPdfGeneratorImplPort() {
        return super.getPort(new QName("http://templates.mobitel.com/", "PdfGeneratorImplPort"), PdfGenerator.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PdfGenerator
     */
    @WebEndpoint(name = "PdfGeneratorImplPort")
    public PdfGenerator getPdfGeneratorImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://templates.mobitel.com/", "PdfGeneratorImplPort"), PdfGenerator.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PDFGENERATORIMPLSERVICE_EXCEPTION!= null) {
            throw PDFGENERATORIMPLSERVICE_EXCEPTION;
        }
        return PDFGENERATORIMPLSERVICE_WSDL_LOCATION;
    }

}
